version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      # Set your production API URL here
      - VITE_API_PATH=https://your-production-api.com
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
