kind: StorageClass 
apiVersion: storage.k8s.io/v1 
metadata:
  name: standard
  
spec:
  provisioner: kubernetes.io/aws-ebs
  parameters:
    type: gp2
    fsType: ext4

  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer